---
jobs:
- job: build_and_pack
  displayName: Build and Pack
  steps:
  - checkout: self
  - task: Npm@1
    displayName: npm install
    inputs:
      command: custom
      verbose: false
      customCommand: ci --no-audit --no-fund
  - task: Npm@1
    displayName: npm run build
    inputs:
      command: custom
      verbose: false
      customCommand: run build
  - task: Npm@1
    displayName: npm pack
    inputs:
      command: custom
      verbose: false
      customCommand: pack
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: $(Build.SourcesDirectory)
      Contents: '*.tgz'
      TargetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: Publish artifacts
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: drop

