---
pool:
  vmImage: ubuntu-latest

trigger:
  branches:
    include:
    - master
    - refs/tags/v*

name: $(date:yyyyMMdd)$(rev:.r)

stages:
- stage: build_and_pack
  displayName: Build And Pack
  dependsOn: []
  jobs:
  - template: build.yaml

- stage: publish_to_npmjs
  displayName: Publish to npmjs
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  dependsOn:
  - build_and_pack
  jobs:
  - template: publish.yaml

