---
jobs:
- job: publish_to_npmjs
  displayName: Publish to npmjs
  steps:
  - download: current
    artifact: drop
    displayName: Download zip package from artifacts
  - task: ExtractFiles@1
    displayName: 'Extract files'
    inputs:
      archiveFilePatterns: '$(Pipeline.Workspace)/**/*.tgz'
      destinationFolder: '$(System.DefaultWorkingDirectory)'
  - task: Npm@1
    displayName: 'npm publish'
    inputs:
      command: custom
      workingDir: '$(System.DefaultWorkingDirectory)/package'
      verbose: false
      customCommand: 'publish --access public'
      customEndpoint: npmjs.org
      publishEndpoint: npmjs.org

